version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile.mongodb
    ports:
      - "27017:27017"
